# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

parameters:
# Service Connection details
- name: ServiceConnection
  type: string
  default: <Service Connection Name>
  displayName: Service Connection

# React Web App Name
- name: WebAppName
  type: string
  default: <Web App Name>
  displayName: React Web App Name
  
variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '${{ parameters.ServiceConnection }}'
  # Web app name
  webAppName: '${{ parameters.WebAppName }}'
  # React build directory
  buildDirectory: 'build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd <Folder path where package.json is present> # <- Optional command. Remove it if everything is in root folder itself.
    npm install
    npm run build --if-present
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/<Folder path where package.json is present else remove this section>/$(buildDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Pipeline Artifact'
  inputs:
    buildType: 'current'
    artifactName: 'drop'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: $(webAppName)'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webApp'
    appName: $(webAppName)
    package: '$(Pipeline.Workspace)/$(Build.BuildId).zip'
